const fs = require('fs');
const path = 'f:/BRIEF/app.js';
let content = fs.readFileSync(path, 'utf8');

const newCurriculum = `const figmaCurriculum = [
    // --- BEGINNER LEVEL (Days 1 - 10) ---
    {
      day: 1,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 1: Auto Layout & Responsive Buttons",
      time: "15 mins",
      concepts: ["#AutoLayout", "#Constraints", "#Padding", "#CornerRadius"],
      objective: "Master Figma Auto Layout to build a fully responsive button component that adapts to text length and respects padding rules.",
      dim: "Auto-resizing",
      radius: "999px (Full Pill)",
      color: "HSL(345, 90%, 68%)",
      steps: [
        "1. Press 'T' and type 'Send Love ❤️' using Inter font (16px, SemiBold).",
        "2. With the text selected, press Shift + A to apply Auto Layout. Notice the Frame icon change.",
        "3. In the Auto Layout panel (right), set Horizontal Padding to 24px and Vertical Padding to 12px.",
        "4. Set the Fill color to HSL(345, 90%, 68%) pink and Corner Radius to 999px.",
        "5. Change the text to a longer phrase to verify the button expands automatically while maintaining the exact padding."
      ],
      tip: "Press Shift + A to instantly wrap any layer in an Auto Layout frame. It's the most powerful shortcut in Figma!",
      videoUrl: "https://www.youtube.com/embed/D4NyQ5iOMF0",
      externalLink: "https://www.youtube.com/watch?v=D4NyQ5iOMF0"
    },
    {
      day: 2,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 2: Advanced Glassmorphism & Depth",
      time: "20 mins",
      concepts: ["#Glassmorphism", "#BackgroundBlur", "#DropShadow", "#InnerShadow"],
      objective: "Create a sophisticated translucent glass card utilizing multiple shadow layers and background blur for a tactile feel.",
      dim: "320px x 200px",
      radius: "24px",
      color: "RGBA(255, 255, 255, 0.4)",
      steps: [
        "1. Draw a rectangle (320x200px) and set Corner Radius to 24px.",
        "2. Set the Fill to Solid White (#FFFFFF) and reduce its specific layer opacity to 40%.",
        "3. Add a 'Background Blur' effect in the Effects panel and set the blur strength to 24px.",
        "4. Add an Inner Shadow (White, 20% opacity, Y: 1, Blur: 0) to simulate a top glass edge highlight.",
        "5. Add a Drop Shadow (Black, 10% opacity, Y: 12, Blur: 32) for realistic elevation.",
        "6. Place a bright, colorful shape behind the card to verify the frosted glass refraction."
      ],
      tip: "To see Background Blur work, the Fill opacity must be less than 100%, and there must be content underneath it!",
      videoUrl: "https://www.youtube.com/embed/vV6c1s1h_5o",
      externalLink: "https://www.youtube.com/watch?v=vV6c1s1h_5o"
    },
    {
      day: 3,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 3: Typography Scales & Fluid Hierarchy",
      time: "20 mins",
      concepts: ["#Typography", "#FontPairing", "#LineHeight", "#Hierarchy"],
      objective: "Establish a robust typographic hierarchy combining display serif fonts with highly legible sans-serif body copy.",
      dim: "340px width Column",
      radius: "16px",
      color: "#2C2C2C & #757575",
      steps: [
        "1. Create an H1 Display heading using 'Playfair Display' at 40px (Bold, 110% line-height, -1% letter spacing).",
        "2. Create an H2 Subheading using 'Inter' at 18px (Medium, #757575, 130% line-height).",
        "3. Create a body paragraph using 'Inter' at 15px (Regular, 150% line-height).",
        "4. Select all text layers and press Shift + A to group them in an Auto Layout column.",
        "5. Set the gap between items to 16px, but manually adjust the gap between H1 and H2 to 8px using individual gap controls."
      ],
      tip: "Use tighter line heights (110-120%) for large headings, and looser line heights (140-160%) for body paragraphs.",
      videoUrl: "https://www.youtube.com/embed/lO3s9T02Vks",
      externalLink: "https://www.youtube.com/watch?v=lO3s9T02Vks"
    },
    {
      day: 4,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 4: Vector Networks & Custom Iconography",
      time: "25 mins",
      concepts: ["#VectorIcons", "#BooleanUnion", "#PenTool", "#CustomShapes"],
      objective: "Move beyond basic shapes by using Boolean operations and the Pen tool to construct a pixel-perfect custom heart icon.",
      dim: "64px x 64px Icon",
      radius: "Vector Smooth",
      color: "Gradient #FF758C -> #FF7EB3",
      steps: [
        "1. Enable the layout grid (Shift + G) and set it to 1px for precision.",
        "2. Draw two perfect circles (40x40px) overlapping each other horizontally by 50%.",
        "3. Draw a polygon triangle, flip it vertically, and position it to connect the bottom arcs of the circles.",
        "4. Select all three shapes, click the Boolean Groups dropdown in the top toolbar, and choose 'Union Selection'.",
        "5. Double-click the resulting shape to enter Vector Network mode, select the sharp bottom node, and add a 2px corner radius.",
        "6. Apply a smooth linear gradient fill (Coral to Magenta) at a 45-degree angle."
      ],
      tip: "Boolean groups are non-destructive! You can always double-click to move the original circles and triangle around.",
      videoUrl: "https://www.youtube.com/embed/D4NyQ5iOMF0",
      externalLink: "https://www.youtube.com/watch?v=D4NyQ5iOMF0"
    },
    {
      day: 5,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 5: Complex Auto Layout & Absolute Positioning",
      time: "25 mins",
      concepts: ["#SpaceBetween", "#AbsolutePosition", "#ZIndex", "#Navbar"],
      objective: "Build a responsive navigation header with centered logos and notification badges using absolute positioning.",
      dim: "100% width Bar",
      radius: "0px",
      color: "#FFFFFF",
      steps: [
        "1. Create a frame for the Navbar (375x64px). Add Auto Layout and set alignment to 'Center' and distribution to 'Space Between'.",
        "2. Place a hamburger menu icon on the left, and a profile avatar on the right.",
        "3. Add a logo text layer in the middle. To force it to absolute center regardless of icon sizes, select it and click 'Absolute Position' in the top right.",
        "4. Create a 16x16px red circle for a notification badge. Drag it inside the avatar frame, and set it to Absolute Position.",
        "5. Pin the badge to the Top and Right constraints of the avatar."
      ],
      tip: "Absolute Positioning inside an Auto Layout frame allows elements to float freely (like notification badges) without disrupting the flex layout.",
      videoUrl: "https://www.youtube.com/embed/lO3s9T02Vks",
      externalLink: "https://www.youtube.com/watch?v=lO3s9T02Vks"
    },
    {
      day: 6,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 6: Foundational Design Tokens & Styles",
      time: "20 mins",
      concepts: ["#ColorStyles", "#DesignTokens", "#TypographyStyles", "#Efficiency"],
      objective: "Establish a scalable foundation by defining and applying reusable Color and Typography styles across multiple components.",
      dim: "Global Styles",
      radius: "N/A",
      color: "Brand Palette",
      steps: [
        "1. Create four distinct color swatches: Primary (#FFB7C5), Secondary (#D8B4FE), Background (#F8F9FA), and Text (#1F2937).",
        "2. Select the Primary swatch, click the 4-dot 'Style' icon in the Fill panel, click '+', and name it 'Color/Primary'. Repeat for others.",
        "3. Select a text layer, click the 4-dot 'Style' icon in the Text panel, and save it as 'Typography/Heading 1'.",
        "4. Create three different UI cards and apply these saved styles to them.",
        "5. Edit the 'Color/Primary' style from the right sidebar (when nothing is selected) and watch all three cards update simultaneously."
      ],
      tip: "Use the forward-slash (/) naming convention (e.g., 'Color/Brand/Primary') to automatically organize styles into folders in the Figma menu.",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 7,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 7: Master Components & Systematic Overrides",
      time: "25 mins",
      concepts: ["#MasterComponent", "#Instances", "#Overrides", "#ResetAll"],
      objective: "Create a robust Master Component, spawn instances, and learn how to manage and reset property overrides.",
      dim: "300x400px Card",
      radius: "20px",
      color: "Component Purple",
      steps: [
        "1. Build a complex Profile Card containing an avatar, name, bio, and a 'Follow' button.",
        "2. Select the parent frame and press Ctrl+Alt+K (Cmd+Option+K) to designate it as a Master Component (purple outline).",
        "3. Hold Alt (Option) and drag the Master Component to create three child Instances.",
        "4. In the instances, override the text, change the avatar images, and change one button's color to gray.",
        "5. Select the modified gray button and click 'Reset all overrides' in the top toolbar to revert it to the Master's styling.",
        "6. Modify the corner radius of the Master Component and observe the instances inherit the structural change while keeping their text overrides."
      ],
      tip: "Never use Master Components directly in your screen designs. Keep them on a separate 'Components' page and only use Instances in your layouts.",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 8,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 8: Prototyping: Smart Animate Fundamentals",
      time: "25 mins",
      concepts: ["#SmartAnimate", "#LayerNaming", "#EasingCurves", "#Transitions"],
      objective: "Engineer a seamless, morphing screen transition utilizing Smart Animate and strict layer naming conventions.",
      dim: "Screen Transition",
      radius: "N/A",
      color: "Interaction Blue",
      steps: [
        "1. Create 'Screen A' containing a small, left-aligned thumbnail image and a short title.",
        "2. Duplicate 'Screen A' to create 'Screen B'.",
        "3. On 'Screen B', scale the thumbnail up to full width and move the title down. CRITICAL: Ensure the layer names for the image and title are exactly identical on both screens.",
        "4. Switch to the Prototype tab (Shift + E). Drag the interaction noodle from the thumbnail on Screen A to Screen B.",
        "5. Set the interaction details: Trigger -> On Click, Action -> Navigate To, Animation -> Smart Animate.",
        "6. Set the Easing to 'Ease Out' with a duration of 400ms. Press Shift + Space to preview the smooth morphing effect."
      ],
      tip: "Smart Animate relies entirely on layer names and hierarchy. If a layer name changes between frames, it will fade instead of morph.",
      videoUrl: "https://www.youtube.com/embed/D4NyQ5iOMF0",
      externalLink: "https://www.youtube.com/watch?v=D4NyQ5iOMF0"
    },
    {
      day: 9,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 9: Clipping, Masks, and Image Manipulation",
      time: "20 mins",
      concepts: ["#ClipContent", "#LayerMasks", "#ImageFills", "#Cropping"],
      objective: "Master non-destructive image cropping techniques using Frame clipping and custom Vector Masks.",
      dim: "Various Shapes",
      radius: "Complex",
      color: "Image Data",
      steps: [
        "1. Technique 1 (Clip Content): Create a Frame (300x300px). Place a high-res image inside it that exceeds the bounds. Check the 'Clip Content' box on the Frame to crop it.",
        "2. Technique 2 (Masking): Draw a complex custom shape with the Pen tool. Place an image layer directly above this shape in the layer tree.",
        "3. Select the custom shape, right-click, and choose 'Use as Mask' (Ctrl+Alt+M). The image is now masked by the vector.",
        "4. Technique 3 (Image Fill): Draw a circle. Go to the Fill panel, change 'Solid' to 'Image', and upload a photo. Use the 'Crop' setting in the image panel to reposition the focus.",
        "5. Combine these techniques to create an overlapping collage of profile pictures."
      ],
      tip: "Using the 'Image Fill' method is usually the cleanest approach for standard geometric avatars and thumbnails.",
      videoUrl: "https://www.youtube.com/embed/vV6c1s1h_5o",
      externalLink: "https://www.youtube.com/watch?v=vV6c1s1h_5o"
    },
    {
      day: 10,
      level: "beginner",
      levelLabel: "Beginner 🐣",
      title: "Day 10: Layer Blending Modes & Gradients",
      time: "25 mins",
      concepts: ["#BlendModes", "#LinearGradient", "#RadialGradient", "#Multiply"],
      objective: "Create rich, atmospheric UI backgrounds by combining complex gradients and photographic blend modes.",
      dim: "Fullscreen",
      radius: "0px",
      color: "Multiply / Overlay",
      steps: [
        "1. Create a large frame (1440x900px) and set the base fill to a dark navy blue (#0B0F19).",
        "2. Add a large, soft Radial Gradient layer originating from the top right, fading from Cyan to 0% opacity. Add another from the bottom left in Magenta.",
        "3. Import a subtle noise texture or photographic image. Place it over the gradients.",
        "4. In the Layer panel (or Fill panel), change the image's Blend Mode from 'Pass Through' to 'Overlay' or 'Multiply'.",
        "5. Adjust the opacity of the texture layer to 15% to achieve a premium, grainy atmospheric effect.",
        "6. Place stark white typography on top to verify contrast and legibility."
      ],
      tip: "Blend modes calculate how colors interact. 'Multiply' darkens colors, 'Screen' lightens them, and 'Overlay' enhances contrast.",
      videoUrl: "https://www.youtube.com/embed/lO3s9T02Vks",
      externalLink: "https://www.youtube.com/watch?v=lO3s9T02Vks"
    },

    // --- INTERMEDIATE LEVEL (Days 11 - 20) ---
    {
      day: 11,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 11: Interactive Components & State Management",
      time: "30 mins",
      concepts: ["#ComponentVariants", "#HoverState", "#PressedState", "#Microinteractions"],
      objective: "Build a single, self-contained Button Component that handles its own Hover and Pressed animation states without needing multiple screens.",
      dim: "Variant Set",
      radius: "12px",
      color: "Interactive",
      steps: [
        "1. Design a primary button. Turn it into a Component (Ctrl+Alt+K).",
        "2. In the Properties panel, click '+' and add a 'Variant' property. Click the purple '+' on the canvas to add a new variant to the set.",
        "3. Name the first variant 'State=Default' and the second 'State=Hover'. Slightly darken the fill of the Hover variant.",
        "4. Add a third variant named 'State=Pressed'. Scale it down by 5% and darken it further.",
        "5. Switch to Prototype mode. Drag a noodle from Default to Hover. Set Trigger: 'While Hovering', Action: 'Change To', Animation: 'Smart Animate 200ms'.",
        "6. Drag a noodle from Hover to Pressed. Set Trigger: 'While Pressing', Action: 'Change To'. Place an instance on a test frame and preview!"
      ],
      tip: "Interactive Components drastically reduce the number of frames needed in your Figma file, making prototypes much lighter and faster.",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 12,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 12: Auto Layout Wrap & Responsive Grids",
      time: "25 mins",
      concepts: ["#AutoLayoutWrap", "#MinMaxWidth", "#TagCloud", "#FluidDesign"],
      objective: "Construct a fluid tag cloud and a responsive product grid that automatically wraps elements to new lines as the container resizes.",
      dim: "Fluid Width",
      radius: "Varies",
      color: "Multi-chip",
      steps: [
        "1. Create 8 different 'Tag' components (e.g., 'Figma', 'Design', 'UI', etc.) using Auto Layout.",
        "2. Select all tags and press Shift + A to wrap them in a parent Auto Layout frame.",
        "3. In the Auto Layout panel, change the direction from 'Horizontal' to 'Wrap' (the curved arrow icon).",
        "4. Set the parent frame's width to 'Fixed' and resize it horizontally. Watch the tags gracefully wrap to subsequent lines.",
        "5. Apply Min Width and Max Width constraints (click the dropdown next to the width input) to prevent the container from getting too narrow or too wide."
      ],
      tip: "Auto Layout Wrap is the key to creating CSS Flexbox-like behaviors in Figma, essential for responsive web design.",
      videoUrl: "https://www.youtube.com/embed/vV6c1s1h_5o",
      externalLink: "https://www.youtube.com/watch?v=vV6c1s1h_5o"
    },
    {
      day: 13,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 13: Advanced Component Properties (UI3)",
      time: "35 mins",
      concepts: ["#BooleanProps", "#TextProps", "#InstanceSwap", "#SidebarControl"],
      objective: "Supercharge a component by exposing Boolean, Text, and Instance Swap properties, allowing complete customization from the right sidebar.",
      dim: "Component Engine",
      radius: "16px",
      color: "System Default",
      steps: [
        "1. Create a complex 'List Item' component containing a left icon, a title, a subtitle, and a right chevron.",
        "2. Select the left icon. In the Layer panel, click the 'Create boolean property' icon. Name it 'Show Icon'.",
        "3. Select the title text. In the Text panel, click the 'Create text property' icon. Name it 'Title Text'.",
        "4. Select the right chevron instance. In the Instance section, click the 'Create instance swap property' icon. Name it 'Right Icon'.",
        "5. Place an instance of this List Item on the canvas. Look at the right sidebar: you can now toggle the icon, edit the text, and swap the chevron without ever double-clicking into the layers!"
      ],
      tip: "Component properties eliminate the need to create hundreds of variants for simple state changes like hiding an icon.",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 14,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 14: Scroll Behavior & Fixed Elements",
      time: "20 mins",
      concepts: ["#ScrollOverflow", "#FixedPosition", "#StickyHeader", "#Prototyping"],
      objective: "Design a realistic mobile app screen with a scrollable content feed, a fixed top header, and a fixed bottom tab bar.",
      dim: "393x852 (iPhone 15)",
      radius: "40px",
      color: "App Background",
      steps: [
        "1. Create an iPhone 15 frame. Inside, place a Header at the top and a Tab Bar at the bottom.",
        "2. Select the Header, switch to Prototype mode, and change Position from 'Scroll with parent' to 'Fixed (stay in place)'. Repeat for the Tab Bar.",
        "3. Create a long Auto Layout column of content that extends far below the bottom of the iPhone frame.",
        "4. Select the main iPhone frame, go to Prototype mode, and set 'Overflow behavior' to 'Vertical'.",
        "5. Present the prototype (Shift + Space) and scroll. The content should scroll smoothly beneath the fixed header and tab bar."
      ],
      tip: "Always ensure your scrollable content layer is positioned *below* your fixed header/footer in the left-hand layer panel.",
      videoUrl: "https://www.youtube.com/embed/D4NyQ5iOMF0",
      externalLink: "https://www.youtube.com/watch?v=D4NyQ5iOMF0"
    },
    {
      day: 15,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 15: Custom Spring Physics in Prototypes",
      time: "25 mins",
      concepts: ["#SpringPhysics", "#BouncyUI", "#CustomEasing", "#MicroInteraction"],
      objective: "Elevate your prototype's feel by replacing linear transitions with highly tuned custom spring physics for organic, tactile animations.",
      dim: "Toggle Switch",
      radius: "999px",
      color: "#34C759",
      steps: [
        "1. Create an iOS-style Toggle Switch component with Off (gray, thumb left) and On (green, thumb right) variants.",
        "2. Wire them up in Prototype mode with an 'On Click' -> 'Change To' interaction.",
        "3. In the Animation settings, choose 'Smart Animate'. Change the Easing dropdown from 'Ease Out' to 'Custom Spring'.",
        "4. Adjust the physics parameters: Set Mass to 1, Stiffness to 300, and Damping to 15.",
        "5. Test the prototype. The switch thumb should snap across and perform a subtle, organic bounce before settling.",
        "6. Experiment with lowering the Damping value to 8 to see an exaggerated, rubber-band effect."
      ],
      tip: "Spring animations feel much more natural and app-like than standard ease curves. Apple's iOS uses spring physics extensively.",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 16,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 16: Advanced Masking & Blend Mode Art",
      time: "30 mins",
      concepts: ["#MeshGradient", "#LayerBlur", "#OrganicGlow", "#Masking"],
      objective: "Combine advanced masking, extreme layer blurs, and blend modes to generate a dynamic, generative-style mesh gradient background.",
      dim: "1440x900 Canvas",
      radius: "0px",
      color: "Mesh Colors",
      steps: [
        "1. Create a large frame with a deep purple background.",
        "2. Use the Pen tool to draw three large, abstract, amoeba-like blobs in bright Cyan, Magenta, and Yellow.",
        "3. Select all three blobs and apply a massive 'Layer Blur' effect (e.g., 200px or 300px) until they dissolve into soft clouds of color.",
        "4. Group the blurred blobs. Create a sharp vector shape (like a giant star or heart) and place it below the group.",
        "5. Select the sharp shape, right-click, and choose 'Use as Mask'. The blurred gradient clouds are now perfectly contained within the sharp shape.",
        "6. Animate the blobs rotating inside the mask using Smart Animate for a mesmerizing effect."
      ],
      tip: "Extreme layer blurs are computationally heavy. If Figma lags, group the blurred layers and 'Rasterize Selection' once you are happy with the look.",
      videoUrl: "https://www.youtube.com/embed/lO3s9T02Vks",
      externalLink: "https://www.youtube.com/watch?v=lO3s9T02Vks"
    },
    {
      day: 17,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 17: Complex Auto Layout Nesting",
      time: "35 mins",
      concepts: ["#NestedAutoLayout", "#FillContainer", "#Flexbox", "#Dashboard"],
      objective: "Architect a complex, responsive dashboard layout by strategically nesting multiple horizontal and vertical Auto Layout frames.",
      dim: "Desktop App",
      radius: "8px",
      color: "Neutral Scale",
      steps: [
        "1. Create a main Desktop frame. Add Auto Layout (Horizontal). This is the master container.",
        "2. Add a Sidebar frame (Fixed Width 240px, Fill Height). Add a Main Content area frame (Fill Container Width, Fill Height).",
        "3. Inside Main Content, add a Topbar frame (Fill Width, Fixed Height 64px) and a Dashboard Grid frame (Fill Width, Fill Height).",
        "4. Inside the Dashboard Grid, use Auto Layout 'Wrap' to place multiple data cards.",
        "5. Set all inner data cards to 'Fill Container' horizontally with a Min-Width of 300px.",
        "6. Resize the main Desktop frame and observe the entire complex architecture adapt flawlessly."
      ],
      tip: "The golden rule of complex responsive design in Figma: Nest Auto Layouts, and ruthlessly apply 'Fill Container' to the inner elements.",
      videoUrl: "https://www.youtube.com/embed/vV6c1s1h_5o",
      externalLink: "https://www.youtube.com/watch?v=vV6c1s1h_5o"
    },
    {
      day: 18,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 18: Horizontal Carousel Prototyping",
      time: "25 mins",
      concepts: ["#HorizontalScroll", "#Carousel", "#OverflowBehavior", "#Pagination"],
      objective: "Build a swipeable movie poster carousel with horizontal scrolling and pagination dots.",
      dim: "Mobile Viewport",
      radius: "16px",
      color: "Dark Mode",
      steps: [
        "1. Create a parent frame representing a mobile screen width (e.g., 393px).",
        "2. Inside, create a very wide Auto Layout row containing 5 large movie poster image cards.",
        "3. Ensure the wide row is wider than the parent frame, and positioned where you want the carousel.",
        "4. Select the *parent frame*, go to Prototype, and set 'Overflow behavior' to 'Horizontal'.",
        "5. Add a set of 5 pagination dots below. Wire up 'On Drag' interactions on the wide row to snap to specific X coordinates using 'Scroll To' actions."
      ],
      tip: "For touch devices, horizontal scrolling (Overflow behavior) is often smoother and easier to implement than complex drag animations.",
      videoUrl: "https://www.youtube.com/embed/D4NyQ5iOMF0",
      externalLink: "https://www.youtube.com/watch?v=D4NyQ5iOMF0"
    },
    {
      day: 19,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 19: Design System Architecture",
      time: "40 mins",
      concepts: ["#DesignSystem", "#FileOrganization", "#AssetExport", "#Handoff"],
      objective: "Structure a professional Figma file utilizing Pages for Covers, Documentation, Foundations (Tokens), Components, and Screens.",
      dim: "File Structure",
      radius: "Organization",
      color: "System Specs",
      steps: [
        "1. Open the Pages panel. Delete the default page and create the following structure: '📔 Cover', '🎨 Foundations', '🧩 Components', '📱 Screens', '🗑️ Archive'.",
        "2. Move all your color/text styles and icons to the 'Foundations' page.",
        "3. Move all your Master Components to the 'Components' page. Organize them into frames labeled 'Inputs', 'Buttons', 'Cards'.",
        "4. Add text annotations explaining usage guidelines next to complex components.",
        "5. Go to the 'Screens' page and ensure ONLY instances are used here, pulling from the component library."
      ],
      tip: "A well-organized file is the difference between a junior designer and a senior product designer. Protect your master components!",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 20,
      level: "intermediate",
      levelLabel: "Intermediate 🌿",
      title: "Day 20: On-Drag Interactive Map Prototype",
      time: "35 mins",
      concepts: ["#OnDragTrigger", "#MapInterface", "#PinchZoom", "#PrototypeState"],
      objective: "Simulate a pan-and-scan map interface using advanced On-Drag triggers and multidirectional Smart Animate.",
      dim: "Fullscreen Map",
      radius: "0px",
      color: "Cartography",
      steps: [
        "1. Place a massive, high-resolution map image (e.g., 2000x2000px) inside a standard phone frame (393x852px). Uncheck 'Clip Content' temporarily.",
        "2. Create Frame A (Map centered on New York). Duplicate to Frame B and move the map image so it centers on Boston.",
        "3. Connect Frame A to B. Set Trigger: 'On Drag', Action: 'Smart Animate'.",
        "4. Connect Frame B back to A with another 'On Drag' trigger.",
        "5. Re-check 'Clip Content' on both frames. Present the prototype and drag the screen to physically pan the map between cities."
      ],
      tip: "On Drag triggers calculate direction automatically based on the difference in layer coordinates between the two frames.",
      videoUrl: "https://www.youtube.com/embed/D4NyQ5iOMF0",
      externalLink: "https://www.youtube.com/watch?v=D4NyQ5iOMF0"
    },

    // --- PRO LEVEL (Days 21 - 30) ---
    {
      day: 21,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 21: Local Variables: Multi-brand Theming",
      time: "40 mins",
      concepts: ["#FigmaVariables", "#DarkMode", "#ThemeModes", "#VariableCollections"],
      objective: "Implement a scalable token system using Figma Local Variables to instantly toggle an entire UI between Light and Dark modes.",
      dim: "Variable Engine",
      radius: "Global Variables",
      color: "Light/Dark Modes",
      steps: [
        "1. Click the canvas background to deselect everything, then click 'Local Variables' in the right sidebar.",
        "2. Create a Collection named 'Primitives' containing raw hex values (e.g., 'blue-500', 'gray-900').",
        "3. Create a second Collection named 'Semantic Tokens'. Create a Color variable named 'bg-primary'.",
        "4. Right-click the 'bg-primary' value and alias it to a Primitive (e.g., 'white'). Add a second Mode column ('Dark') and alias it to 'gray-900'.",
        "5. Apply the 'bg-primary' variable to a complex UI screen.",
        "6. Select the screen frame, go to the Layer panel, click the Variables icon, and switch the mode from Light to Dark. Watch the entire UI instantly invert!"
      ],
      tip: "Never hardcode hex values in Semantic Tokens. Always alias them to Primitives. This ensures sweeping brand color updates require only changing one primitive value.",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 22,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 22: Advanced Prototyping with Math Variables",
      time: "45 mins",
      concepts: ["#NumberVariables", "#Expressions", "#ConditionalLogic", "#ShoppingCart"],
      objective: "Engineer a fully functional e-commerce shopping cart using Number Variables, Math Expressions, and String interpolation.",
      dim: "Logic Engine",
      radius: "16px",
      color: "Dynamic Data",
      steps: [
        "1. Open Local Variables and create two Number variables: `itemPrice` (set to 49) and `cartCount` (set to 0).",
        "2. Create a UI with an 'Add to Cart' button, a text layer displaying the cart quantity, and a text layer displaying the Total Price.",
        "3. Select the cart quantity text. In the Text panel, click the Variables icon and bind it to `cartCount`.",
        "4. Select the 'Add to Cart' button. In Prototype mode, add an 'On Click' interaction -> 'Set Variable'.",
        "5. Configure it to set `cartCount` to expression: `cartCount + 1`.",
        "6. Add a second 'Set Variable' action to the same click event: set a new string variable `displayTotal` to expression: `'$' + (itemPrice * cartCount)`.",
        "7. Bind the Total Price text layer to `displayTotal` and test the live calculating cart!"
      ],
      tip: "You can stack multiple 'Set Variable' and 'Conditional' actions on a single click event to create complex programmatic logic without code.",
      videoUrl: "https://www.youtube.com/embed/lO3s9T02Vks",
      externalLink: "https://www.youtube.com/watch?v=lO3s9T02Vks"
    },
    {
      day: 23,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 23: Component Nesting & Exposure Architecture",
      time: "35 mins",
      concepts: ["#ExposedInstances", "#NestedComponents", "#PropertyOverrides", "#AtomicDesign"],
      objective: "Architect a complex 'Data Table' organism utilizing deep component nesting and 'Expose Nested Instances' to streamline overrides.",
      dim: "Complex Organism",
      radius: "0px",
      color: "System Borders",
      steps: [
        "1. Create 'Atom' components: Cell Text, Cell Icon, Checkbox.",
        "2. Create 'Molecule' components: Table Header Row, Table Data Row. Nest the Atoms inside these.",
        "3. Create the 'Organism' component: Data Table, containing a Header Row and 5 Data Rows.",
        "4. Select the main Data Table Master Component. In the Properties panel, click the gear icon next to 'Nested Instances'.",
        "5. Check the boxes to expose the properties of the Checkbox and Icon atoms.",
        "6. Drop an instance of the Data Table into a design. You can now toggle checkboxes and swap icons for any row directly from the top-level properties panel, without clicking 5 layers deep!"
      ],
      tip: "Exposing nested instances is crucial for building maintainable design systems. It prevents users from constantly digging through the layer tree.",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 24,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 24: Responsive Prototyping with Auto Layout",
      time: "30 mins",
      concepts: ["#ResponsivePrototype", "#Breakpoints", "#MinMaxWidth", "#FluidTesting"],
      objective: "Build a single prototype screen that seamlessly transitions between mobile, tablet, and desktop layouts when manually resized.",
      dim: "Fluid Viewport",
      radius: "Responsive",
      color: "Breakpoint Grids",
      steps: [
        "1. Create a large frame (1440px wide). Set it to Auto Layout (Vertical, Fill Container).",
        "2. Build a Navigation bar inside that uses 'Space Between'. Group the links in an Auto Layout frame and set it to 'Wrap'.",
        "3. Build a Hero section with a Left Text column and Right Image column. Set the parent to 'Wrap'.",
        "4. Crucial step: Set the Min Width of the Left Text column to 300px, and the Image column to 300px.",
        "5. Ensure the parent container has a Max Width of 1200px and is centered.",
        "6. Grab the edge of the master frame and drag it inwards. Watch the columns stack vertically and the navigation wrap smoothly to simulate CSS media queries."
      ],
      tip: "Figma UI3's Min/Max width and Auto Layout Wrap finally allow true responsive design testing directly on the canvas without third-party plugins.",
      videoUrl: "https://www.youtube.com/embed/vV6c1s1h_5o",
      externalLink: "https://www.youtube.com/watch?v=vV6c1s1h_5o"
    },
    {
      day: 25,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 25: 3D Skewing & Isometric Device Mockups",
      time: "40 mins",
      concepts: ["#Isometric", "#3DRotation", "#MockupGenerator", "#Presentation"],
      objective: "Transform flat UI screens into stunning, presentation-ready 3D isometric device mockups using Figma plugins and precise skewing.",
      dim: "Presentation Canvas",
      radius: "Device Bezel",
      color: "Studio Lighting",
      steps: [
        "1. Design a polished mobile app screen (393x852).",
        "2. Install and run a community plugin like 'Vectary 3D' or 'Rotary'. (Alternatively, use manual isometric projection: Rotate -45deg, Skew +15deg).",
        "3. Map your flat UI frame onto a 3D iPhone clay model provided by the plugin.",
        "4. Adjust the lighting, shadow angle, and device color to match your brand.",
        "5. Export the 3D asset as a high-res PNG and place it into a sleek Dribbble-style presentation shot.",
        "6. Add a soft, colorful mesh gradient background and floating geometric glass spheres to complete the aesthetic."
      ],
      tip: "Plugins are essential for true 3D perspective mapping. Manual skewing distorts text and borders, whereas plugins map the pixel data accurately.",
      videoUrl: "https://www.youtube.com/embed/lO3s9T02Vks",
      externalLink: "https://www.youtube.com/watch?v=lO3s9T02Vks"
    },
    {
      day: 26,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 26: Micro-animation with GIF & Video Fills",
      time: "25 mins",
      concepts: ["#GIFFills", "#VideoIntegration", "#AnimatedPrototype", "#MicroMotion"],
      objective: "Embed high-fidelity motion graphics (GIFs and MP4s) directly into components to simulate rich, complex app states.",
      dim: "Media Container",
      radius: "24px",
      color: "Video Pixels",
      steps: [
        "1. Create a 'Success State' modal dialog component.",
        "2. Instead of a static checkmark, draw a square frame above the text.",
        "3. Change the Fill mode from 'Solid' to 'Video' (or Image -> GIF). Upload a high-quality Lottie animation exported as a GIF, or an MP4 of a custom 3D checkmark.",
        "4. Set the Fill crop mode to 'Fill' or 'Fit' depending on the aspect ratio.",
        "5. Wire a button on a previous screen to open this modal using the 'Open Overlay' prototype action.",
        "6. Run the prototype. The video/GIF will auto-play instantly when the overlay appears, providing a premium feel."
      ],
      tip: "Keep video files under 5MB for performance. GIFs are great for small micro-interactions, but MP4s are significantly more performant and higher quality for large areas.",
      videoUrl: "https://www.youtube.com/embed/D4NyQ5iOMF0",
      externalLink: "https://www.youtube.com/watch?v=D4NyQ5iOMF0"
    },
    {
      day: 27,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 27: Boolean Logic & Conditional Prototyping",
      time: "40 mins",
      concepts: ["#ConditionalLogic", "#IfElse", "#FormValidation", "#Variables"],
      objective: "Program a functional password validation sequence utilizing Boolean Variables and If/Else logic blocks in the Prototype panel.",
      dim: "Logic Gate",
      radius: "8px",
      color: "Error Red / Success Green",
      steps: [
        "1. Create a Boolean variable named \`isPasswordValid\` set to \`false\`.",
        "2. Design a Login screen with a 'Submit' button. Create a 'Success Dashboard' screen and an 'Error Modal' overlay.",
        "3. Select the 'Submit' button. Add an 'On Click' interaction, and choose 'Conditional'.",
        "4. Set the IF condition: \`if isPasswordValid == true\`.",
        "5. Under the IF block, add action: \`Navigate to -> Success Dashboard\`.",
        "6. Under the ELSE block, add action: \`Open Overlay -> Error Modal\`.",
        "7. (Optional) Create a toggle switch that sets \`isPasswordValid\` to \`true\` to test both pathways!"
      ],
      tip: "Conditionals turn Figma from a static flipbook into a functional logic engine, allowing you to build highly realistic usability tests.",
      videoUrl: "https://www.youtube.com/embed/lO3s9T02Vks",
      externalLink: "https://www.youtube.com/watch?v=lO3s9T02Vks"
    },
    {
      day: 28,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 28: Dev Mode, Handoff Specs & CSS Flexbox",
      time: "30 mins",
      concepts: ["#DevMode", "#CSSHandoff", "#RedlineSpecs", "#CodeInspection"],
      objective: "Transition into the developer's mindset: audit your file using Dev Mode, generate CSS/React snippets, and annotate layout specs.",
      dim: "Code Inspector",
      radius: "Syntax Highlighting",
      color: "VS Code Theme",
      steps: [
        "1. Finish a complex layout. Press Shift + D to toggle Dev Mode.",
        "2. Select a nested Auto Layout frame. Observe the generated CSS Flexbox code in the right panel (notice \`display: flex\`, \`gap\`, \`padding\`).",
        "3. Switch the code generation language from CSS to React or iOS Swift to see how the platform translates your design.",
        "4. Use the 'Measure' tool to click between elements and verify that all margins and paddings adhere to a strict 8pt grid system.",
        "5. Use the 'Annotations' feature to leave a note for the developer explaining a specific z-index requirement or transition curve."
      ],
      tip: "A true Pro designer builds their Figma files mirroring how a developer writes code (using Variables for tokens, Auto Layout for Flexbox, and Components for React elements).",
      videoUrl: "https://www.youtube.com/embed/kYJmQ67H9t4",
      externalLink: "https://www.youtube.com/watch?v=kYJmQ67H9t4"
    },
    {
      day: 29,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 29: Plugin Development & Automation Intro",
      time: "45 mins",
      concepts: ["#FigmaAPI", "#Plugins", "#Automation", "#Scripter"],
      objective: "Take the ultimate step: write a basic script using the 'Scripter' plugin to automate a repetitive design task.",
      dim: "Console Terminal",
      radius: "0px",
      color: "#000000",
      steps: [
        "1. Install the 'Scripter' plugin from the Figma Community (it allows writing JS directly in Figma).",
        "2. Run Scripter. You will see a code editor. We will write a script to generate 10 randomly colored squares.",
        "3. Type the following logic (conceptually): Loop 10 times. Create a rectangle node. Set its X/Y position based on the loop index. Set its fill to a random RGB value.",
        "4. Example API call: \`const rect = figma.createRectangle(); rect.x = i * 110;\`",
        "5. Execute the script and watch Figma generate the shapes instantly.",
        "6. (No coding experience? Use the 'Similayer' or 'Automator' plugins to achieve complex bulk actions without writing code!)"
      ],
      tip: "The Figma Plugin API is incredibly powerful. Learning basic JavaScript opens the door to automating hours of tedious design work.",
      videoUrl: "https://www.youtube.com/embed/vV6c1s1h_5o",
      externalLink: "https://www.youtube.com/watch?v=vV6c1s1h_5o"
    },
    {
      day: 30,
      level: "pro",
      levelLabel: "Pro 👑",
      title: "Day 30: The Grand Capstone Architecture",
      time: "60+ mins",
      concepts: ["#MasterCapstone", "#EndToEnd", "#DesignSystem", "#LogicPrototype"],
      objective: "The Final Challenge: Synthesize Variables, Auto Layout, Components, and Conditional Logic into a production-ready, multi-themed, interactive prototype.",
      dim: "The Final Build",
      radius: "Perfection",
      color: "Gold Graduation 👑",
      steps: [
        "1. **Foundations**: Establish a full token variable system (Colors, Spacing, Radii) with Light and Dark modes.",
        "2. **Components**: Build a scalable UI kit (Buttons, Inputs, Cards, Navbars) utilizing nested instances, boolean properties, and interactive states.",
        "3. **Layouts**: Construct 3 high-fidelity screens (Home, Detail, Checkout) strictly using Auto Layout and your component library. Ensure they are fully responsive.",
        "4. **Logic**: Wire the screens together. Use conditional logic for form validation, number variables for a functional shopping cart, and custom spring animations for transitions.",
        "5. **Handoff**: Organize the file meticulously, run Dev Mode to check for hardcoded values, and share the prototype link.",
        "6. **Graduation**: Celebrate! You have mastered Figma from the ground up! 🎉"
      ],
      tip: "You are officially a Figma Pro! The skills you've learned here are identical to those used by senior product designers at top tech companies. You're ready! 🎓👑💖",
      videoUrl: "https://www.youtube.com/embed/lO3s9T02Vks",
      externalLink: "https://www.youtube.com/watch?v=lO3s9T02Vks"
    }
  ];`;

content = content.replace(/const figmaCurriculum = \[[^]*?\n  \];/, newCurriculum);

fs.writeFileSync(path, content);
console.log('Successfully updated app.js!');
